# Generated by Django 4.2.7 on 2024-09-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expensesitem_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesitem',
            name='expenses',
        ),
        migrations.AddField(
            model_name='expensesitem',
            name='expesnses',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expensesitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expensesitem',
            name='purpose',
            field=models.CharField(choices=[('B', 'b'), ('A', 'a')], max_length=100, null=True),
        ),
    ]
