# Generated by Django 4.2.7 on 2024-09-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_expensesitem_expenses_expensesitem_expesnses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesitem',
            name='expesnses',
        ),
        migrations.AlterField(
            model_name='expensesitem',
            name='purpose',
            field=models.CharField(choices=[('A', 'a'), ('B', 'b')], max_length=100, null=True),
        ),
    ]
