# Generated by Django 4.2.16 on 2024-09-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose',
            name='code',
        ),
    ]
