# Generated by Django 4.2.16 on 2024-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_purpose_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesitem',
            name='purpose',
            field=models.CharField(choices=[(1, 'Einkauf'), (2, 'Saufen'), (3, 'Trinken'), (4, 'Wohnene')], max_length=100, null=True),
        ),
    ]
