# Generated by Django 4.2.16 on 2024-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_expensesitem_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesitem',
            name='purpose',
            field=models.IntegerField(choices=[(1, 'Einkauf'), (2, 'Saufen'), (3, 'Trinken'), (4, 'Wohnene')], null=True),
        ),
    ]
