# Generated by Django 4.2.16 on 2024-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_expensesitem_purpose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purpose',
        ),
        migrations.AlterField(
            model_name='expensesitem',
            name='purpose',
            field=models.CharField(choices=[('B', 'b'), ('A', 'a')], max_length=100, null=True),
        ),
    ]
