# Generated by Django 4.2.16 on 2024-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_purpose_alter_expensesitem_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesitem',
            name='purpose',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
