# Generated by Django 4.2.16 on 2024-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_networth'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesitem',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
